name: CI pipeline
run-name: run by ${{  github.actor  }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.300'

    - name: Executing the build command
      working-directory: ./src
      run: dotnet build Review-Filmes.sln
